import ThemeProvider from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toast";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import localfont from "next/font/local";
import "./globals.css";

const roboto = Roboto({ subsets: ["latin"], variable: "--font-sans" });

const persianFont = localfont({
  src: "../fonts/persian-font.ttf",
  variable: "--font-persian",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      className={cn(
        roboto.variable,
        persianFont.variable,
        "h-full",
        "antialiased",
        "font-sans",
      )}
      suppressHydrationWarning
      lang="en"
    >
      <body>
        <div className="grid grid-rows-[auto_1fr_auto] gap-8 min-h-svh">
          <ThemeProvider
            disableTransitionOnChange
            defaultTheme="system"
            attribute="class"
            enableSystem
          >
            {children}
            <Toaster timeout={3000} />
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
